A user can add an item to their cart.
ChrisJVoss/audio-zone pull request #7
Opened 2017-06-19 21:30 UTC by ChrisJVoss

![screen shot 2017-06-19 at 2 28 22 pm](https://user-images.githubusercontent.com/29046393/27306757-be9b90e0-54fb-11e7-9f0f-bd94b0041e3f.png)

![screen shot 2017-06-19 at 2 28 55 pm](https://user-images.githubusercontent.com/29046393/27306763-c3a47994-54fb-11e7-843d-807128f50282.png)

![screen shot 2017-06-19 at 2 29 18 pm](https://user-images.githubusercontent.com/29046393/27306769-c722d700-54fb-11e7-9f78-b266f32b1233.png)

2017-06-19 22:53 UTC, victormejia requested changes
great job so far

2017-06-19 22:53 UTC, victormejia commented on main.js
> +  // createReturnButton(product)
if this is no longer needed, let's get rid of it

2017-06-19 22:53 UTC, victormejia commented on main.js
> +  count = cartSize.length
don't forget to declare `var count`, otherwise you're declaring a global variable

2017-06-19 22:53 UTC, victormejia commented on main.js
> +  cart.unshift(itemList[cartId]);
is this to have the latest items added to the front?

2017-06-19 22:57 UTC, ChrisJVoss commented on main.js
> +  cart.unshift(itemList[cartId]);
Yea, it made sense to me that the newest items would come first? Like they are at the top of the shopping cart. Should I change it to push?

2017-06-20 04:18 UTC, victormejia approved these changes
great job!

2017-06-20 16:45 UTC, merged